# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Logrotate | Configure rotation config files.'
  become: yes
  template:
    src: '{{ item.template | default(logrotate_config_template) }}'
    dest: '{{ logrotate_conf_path }}/{{ item.name }}'
    state: '{{ item.state | default(omit) }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ logrotate_config_files }}'
  when: 'logrotate_config_files | default(None) != None'

- name: 'Logrotate | Force file rotation.'
  become: yes
  command: 'logrotate --force {{ logrotate_conf_path }}/{{ item.name }}'
  with_items: '{{ logrotate_config_files }}'
  when: 'logrotate_config_files | default(None) != None and (logrotate_force_all or item.force is defined and item.force)'